### ISSUE TITLE
Mathematics?

### ISSUE THREAD

**Issue by edsu** [davidmcclure/open-syllabus-project#2]
A [few of us](https://twitter.com/kayiwa/status/690916596357951488) were curious about the lack of Mathematics as a field to filter by. Is there an interesting story there?

**Comment by davidmcclure** [comment]
Whoops, this is because mathematics isn't marked as a "primary" field in our source spreadsheet. Fixed by d5dd105286df6dccd531a867658421af746e8d30. (This will get surfaced in the results next time we run field extraction.)

Thanks!
